### ISSUE TITLE
make run does not work on Mac

### ISSUE THREAD

**Issue by svenallers** [macalimlim/godot-rust-template#43]
`make run` does not work on Mac because the `-b` option is not supported. Executing the command result in:
```
mv -b ./target/x86_64-apple-darwin/debug/*.dylib ./lib/x86_64-apple-darwin
mv: illegal option -- b
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
```

On: MacOS Monterey 12.0.1

**Comment by macalimlim** [comment]
@svenallers Have you installed coreutils? You can refer to the [wiki](https://github.com/godot-rust/godot-rust-template/wiki)

**Comment by macalimlim** [comment]
Closing this issue, the template is now using cargo-make instead of make, thus removing the dependency to gnu coreutils...
